version: "3"
services:
  server:
    image: pinked/docker-glusterfs
    networks:
      - storage
      - proxy
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=gluster.p.cns.me
        - com.df.servicePath=/
        - com.df.port=9000
    volumes:
      - /brick:/brick/
    environment:
      - ROOTUSER=root
      - ROOTPASS=true
      - PEER_DISCOVERY_NAME=server

networks:
  storage:
    external: true
  proxy:
    external: true